---
# ---------------------------------------------
# Verify python installation
# ---------------------------------------------
- set_fact:
    # Translate full python_version (3.4.5) to the MAJOR.MINOR value, like "3.4"
    python_version_base: "{{ python_version|regex_replace('(\\d+\\.\\d+)\\..*$', '\\1') }}"
  when: ansible_version.major >= 2

- set_fact:
    # Translate full python_version (3.4.5) to the MAJOR.MINOR value, like "3.4"
    # Prior to ansible 2.0, you needed to escape backreferences (e.g. \\1) with 4 backslashes (\\\\)
    python_version_base: "{{ python_version|regex_replace('(\\d+\\.\\d+)\\..*$', '\\\\1') }}"
  when: ansible_version.major < 2

- set_fact:
    python_exec: "python{{ python_version_base }}"

- name: check if python version {{ python_version }} installed
  command: "which {{ python_install_dir }}/bin/{{ python_exec }}"
  changed_when: False

