---
# ---------------------------------------------
# Verify python installation on this server
# Input variables:
#   - python_version
#   - python_install_dir
# ---------------------------------------------
- set_fact:
    ## Translate full python_version (3.4.5) to the MAJOR.MINOR value, like "3.4"
    python_version_base: "{{ '.'.join(python_version.split('.')[:2]) }}"

- set_fact:
    python_exec: "python{{ python_version_base }}"

- name: check if python version {{ python_version }} installed
  command: "which {{ python_install_dir }}/bin/{{ python_exec }}"
  changed_when: False
