---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml" 

- include: apache.yml

- name: Check if mod_wsgi is installed
  stat:
    path: "{{ apache_libexecdir }}/mod_wsgi.so"
  register: wsgi_exists
  changed_when: False

- include: python.yml
  when: wsgi_force_install|bool or wsgi_exists.stat.exists == False

- include: dependencies.yml
  when: wsgi_force_install|bool or wsgi_exists.stat.exists == False

- include: install.yml
  when: wsgi_force_install|bool or wsgi_exists.stat.exists == False

